# docker-compose.yml
 

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - portfolio-network

  # Pour le développement (facultatif)
  portfolio-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: portfolio-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge